name: Marafie
favicon: null
layout_spectrum: 0.0816184557043016
typography_spectrum: 0.5353128486312926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6408044174313545
  lightness: 0.6422999550122768
  saturation: 0.6326763103716075
  rhythmicContrast: 0.31003036978654563
purpose: []
